server:
  port: 8090

spring:
  application:
    name: coreProject

  docker:
    compose:
      enabled: false

  datasource:
    # 1. JDBC 드라이버 클래스 이름 (PostgreSQL)
    driver-class-name: org.postgresql.Driver

    # 2. DB 접속 URL
    # [localhost]: 서버 주소 (로컬에서 실행 시)
    # [5432]: PostgreSQL 기본 포트
    # [데이터베이스명]: 이전에 생성한 데이터베이스 이름
    url: ${DB_URL:jdbc:postgresql://localhost:5432/babyhands}

    # 3. DB 사용자 이름
    username: ${DB_USERNAME:}

    # 4. DB 비밀번호
    password: ${DB_PASSWORD:}

  jpa:
    # JPA 구현체로 Hibernate 사용
    hibernate:
      ddl-auto: update
    # SQL 쿼리 로깅
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            # 소셜 로그인 후 서버로 리다이렉트될 URI. 이 URI는 Google Cloud Console에 등록해야 합니다.
            redirect-uri: ${GOOGLE_REDIRECT_URL:}
            scope: ${GOOGLE_SCOPE:}
          kakao:
            client-id: ${KAKAO_CLIENT_ID:}
            client-secret: ${KAKAO_CLIENT_SECRET:}
            redirect-uri: ${KAKAO_REDIRECT_URL:}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: ${KAKAO_SCOPE:}
            client-name: Kakao
          naver:
            client-id: ${NAVER_CLIENT_ID:}
            client-secret: ${NAVER_CLIENT_SECRET:}
            redirect-uri: ${NAVER_REDIRECT_URI:}
            authorization-grant-type: authorization_code
            scope: ${NAVER_SCOPE:}
            client-name: Naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

app:
  auth:
    token-secret: ${JWT_TOKEN_SECRET:} # JWT 서명에 사용할 비밀 키

    # 필수: Access Token의 만료 시간 (밀리초) - 예: 30분
    access-token-expiration-msec: ${ACCESS_TOKEN_EXPIRATION:1800000}

    # 필수: Refresh Token의 만료 시간 (밀리초) - 예: 7일
    refresh-token-expiration-msec: ${REFRESH_TOKEN_EXPIRATION:604800000}